version: '3'
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env.docker
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  api:
    build: .
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    depends_on:
      database:
        condition: service_healthy

volumes:
  pg-data:
