version: '3'
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env.docker
    volumes:
      - pg-data:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - .env.docker
    ports:
      - 3000:3000
    depends_on:
      - database

volumes:
  pg-data:
